### ISSUE TITLE
How  to regenerated the expected hashes for the SM and eapp？

### ISSUE THREAD

**Issue by RMheng** [keystone-enclave/keystone-demo#11]
I tried keystone demo, but got attestation failure. It seems that sm_expected_hash(from the riscv-pk/hash) is different from the sm hash in the report.

Beside that, I'm also refused about how the report got the sm hash and then sent to client? To my understanding，attestation report which server sends to client includes sm hash，enclave hash and public key.But relevant code in the attest_and_establish_channel from the server_eapp/server_eapp.c describes as:

```
attest_enclave((void*) buffer, server_pk, crypto_kx_PUBLICKEYBYTES);
ocall_send_report(buffer, 2048);

ocall_wait_for_client_pubkey(client_pk, crypto_kx_PUBLICKEYBYTES);
channel_establish();
```
The above codes seems to only send the server pk and then wait the message from client.

Thanks for your reading and reply!

**Comment by dkohlbre** [comment]
Yes, the expected hashes have to be regenerated when we change the SM. Since the demo is stand-alone, we don't regenerate those hashes often. The easiest way to regenerate that hash is to use the `build-hash-using-qemu` make target in the demo. Let us know if that has problems.

`attest_enclave` generates a full attestation report via SBI call to the SM, and puts it in the buffer. The eapp can only request a small additional buffer to be included in that report (in this case, the server_pk which is for ECDH parameters.) This report includes enclave/SM hashes and other information.

By having the SM construct the report with SM/enclave hashes and sign with the SM key, the enclave cannot forge a report. This ensures that when the client gets a valid report they can be confident they are establishing a channel with a legitimate enclaved server.

**Comment by RMheng** [comment]
Thanks for your help and explanation. By using `make getandsethash`, I succeeded in regenerating expected hashes and got attested!
