### ISSUE TITLE
keystone.h: No such file or directory

### ISSUE THREAD

**Issue by dunamist** [keystone-enclave/keystone-demo#14]
Hey, I got this error when I run quickstart.sh, but I couldn't find this file anywhere. So, is there any solution? Please tell me. Thank you!!!
![error](https://user-images.githubusercontent.com/56823964/93730417-11125a80-fbfb-11ea-9a21-479833cebd78.png)

**Comment by dunamist** [comment]
I also find 6 keystone.h files in keystone, but they are just different.

**Comment by dunamist** [comment]
This happened when compiling libsodium_client.

**Comment by dayeol** [comment]
This is because Keystone SDK is updated and is not backward compatible.

Is your KEYSTONE_SDK_DIR set to the SDK install directory?
The install directory must contain `include/` that contains a bunch of header files.
If so, please try to change "keystone.h" by "host/keystone.h".

Also you will see a bunch of errors about undefined symbol `Keystone`.
We have re-defined the class names and put all of them into a namespace `Keystone`.
So the old `Keystone` class is now `Keystone::Enclave`
and the old `Params` class is now `Keystone::Params` and so on.

I'll try to fix this as soon as possible, because it's very easy to fix.

**Comment by dayeol** [comment]
Please refer to the SDK change that causes this problem: https://github.com/keystone-enclave/keystone-sdk/pull/55

**Comment by dunamist** [comment]
Thank you for your suggestion, but there are still some others problems. I choose to give it up, and wait for this repo updated.
