### ISSUE TITLE
ERROR DURING BUILDING

### ISSUE THREAD

**Issue by NirjharRoy** [keystone-enclave/keystone-demo#4]
When I run ./quick-start.sh I am getting the following error after sometime 
trusted_client/trusted_client.cpp: In function 'void trusted_client_get_report(void*, int)':
trusted_client/trusted_client.cpp:54:10: error: 'class Report' has no member named 'printPretty'
   report.printPretty();
          ^~~~~~~~~~~
Makefile:47: recipe for target 'trusted_client.riscv' failed
make: *** [trusted_client.riscv] Erro

After commenting out the line 54 of Trusted_client.cpp the build is successuful  but I am getting page fault at 0x20000

**Comment by dkohlbre** [comment]
Hi,
The demo is currently targeted against the `dev` branch of keystone, I suspect you are on `master`.

(The page fault is happening due to a change in how the driver allocates memory for enclave heaps)

I'll make sure the documentation and quick-start make sure keystone is on `dev`

**Comment by NikhilBansal1999** [comment]
Hi,
Can you explain a bit more about page fault? I wrote a sample enclave which asks the user for input and computes Fibonacci. If I simply add 1 to the user input and print the value, everything is fine. But if I try calling the function that calculates Fibonacci, I get a page fault.

**Comment by dkohlbre** [comment]
Hi,
Can you confirm that you are on the latest dev branch? Master has not been bumped for a little while.

If you are on dev, can you give us any more information about the crash? Where is it page faulting?
If its in the application, and your fib example is recursive, you may be just running out of stack.

**Comment by NikhilBansal1999** [comment]
I am currently on the master branch.
The code below causes the crash:
unsigned long fibonacci_rec(unsigned long in){
  if( in <= 1)
    return 1;
  else
    return fibonacci_rec(in-1)+fibonacci_rec(in-2);
}

void EAPP_ENTRY fibonacci_calculator()
{
  unsigned long number = ocall_get_number();
  unsigned long return_answer = fibonacci_rec(number);
  //unsigned long return_answer = number + 1;
  ocall_print_value(return_answer);
  EAPP_RETURN(return_answer);
}
if I un-comment "return_answer=number+1;" and comment the line above it, the code works fine.
Also, the program crashes for small values too. The program crashes even if the number is equal to 1.

**Comment by dkohlbre** [comment]
There are a couple things happening, one is that the master branch is (our fault) quite out of date compared to what is on the dev branch. We'll bump that soon. For now please try using the `dev` branch.

Second, the issue you are having is unrelated to the issue above, if you think there is a problem with your binary getting loaded or with stack sizes please open a new issue about that.

That said, I'm also still not sure what the issue you are having is, since there are dozens of reasons your code might be crashing. Where is the page fault occurring (what address is faulting, and what is the cause value given by the runtime?)
